### ISSUE TITLE
Review API of messages/kerberos types

### ISSUE THREAD

**Issue by ltp1405** [ltp1405/kerberos-simple#21]
### We should review the API of kerberos related types to see if they are:
- User-friendly
- Rust idiomatic

### Something to check for:
- Implemented/derived traits: enough? unnecessary?
- Implemented methods: good name? arguments?
- Documentation should be provided if the usage is not intuitive enough

### Candidate:
- [x] name of the constructor of `PrincipalName` (`try_from`): is it confused? clashed with trait `TryFrom`
- [x] `PrincipalName`'s `NameType`: should it be i32 with special meanings or should it be its own type?

### Please comment anything you found that need to be discussed here

**Comment by ltp1405** [comment]
This issue is also related to #15

**Comment by phatalways-sleeping** [comment]
In case PrincipalName's NameType is changed, AddressHost's AddressType should also be due to the similar reasons. Beside that, ApplicationTags in application_tags modules should also be converted to Enum
